algo = input('Digite algo: ')
print('O tipo primito desse valor é:', type(algo))
print('Só tem espaços? ', algo.isnumeric())
print('É alfabético?', algo.isalpha())
print('É Numérico?', algo.isnumeric())
print('É alfanumérico?', algo.isalnum())
print('Está tudo escrito em minúsculo?', algo.isupper())
print('É um número decimal?', algo.isdecimal())
print('É um identificador?', algo.isidentifier())
print('Pode ser impresso?', algo.isprintable())
print('Começa com letras maiúsculas e termina com minúsculas?', algo.istitle())
print('É um dígito?', algo.isdigit())
